import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv(r"C:\Users\GOURAV SHARMA\OneDrive\Documents\real_projects\netflix_titles.csv")
#cleaning the data
df = df.dropna(subset = ['type','country', 'release_year','rating','duration'])
type_counts = df['type'].value_counts()
plt.figure(figsize=(6,4))
plt.bar(type_counts.index , type_counts.values , color = ('green','blue'))
plt.title('Number of Movies and tv shows')
plt.ylabel('type')
plt.xlabel('number of movies or TV shows')
plt.tight_layout()
plt.savefig('movies vs tv shows',dpi = 300)
plt.show()
rating_counts = df['rating'].value_counts()
plt.figure(figsize = (6,4))
plt.pie(rating_counts,labels = rating_counts.index,autopct = '%1.1f%%' , startangle=90)
plt.title('percentage of content rating')
plt.savefig('contents_rating.png')
plt.show()
movie_df = df[df['type'] == 'Movie'].copy()
movie_df['duration_int'] = movie_df['duration'].str.replace('min','').astype(int)
plt.figure(figsize = (8,6))
plt.hist(movie_df['duration_int'],bins =30,color = 'purple',edgecolor = 'black')
plt.title('Duration of the movie')
plt.xlabel('duration in minutes')
plt.ylabel('Number of movies')
plt.savefig('movie_duration.png')
plt.show()
release_count = df['release_year'].value_counts().sort_index()
plt.figure(figsize = (8,9))
plt.scatter(release_count.index,release_count.values,color = 'Red',marker = 'o',label = 'Number of released shows')
plt.xlabel('Year of making')
plt.ylabel('Number of shows')
plt.savefig('number_of_shows.png')
plt.show()
top_countries = df['country'].value_counts().head(10)
plt.figure(figsize=(9,10))
plt.bar(top_countries.index,top_countries.values,color = 'skyblue',label = 'Top 10 countries in production')
plt.xlabel('Countries')
plt.ylabel('Number of shows')
plt.tight_layout()
plt.savefig('top_10_countries.png')
plt.show()
content_by_year = df.groupby(['release_year','type']).size().unstack().fillna(0)
fig, ax = plt.subplots(1,2,figsize = (8,9))
ax[0].plot(content_by_year.index,content_by_year['Movie'],color ='Yellow')
ax[0].set_title('Movies by year')
ax[1].plot(content_by_year.index,content_by_year['TV Show'],color = 'lightgreen')
ax[1].set_title('TV Shows by year')
plt.suptitle('comparison of movies and Tv Shows')
plt.tight_layout()
plt.savefig('movie_tvshow_comparisons.png')
plt.show()